FROM alpine:latest

ADD docker/repositories /etc/apk

RUN apk add php7 php7-fpm php7-opcache php7-gd php7-mysqli php7-zlib php7-curl php7-mbstring php7-json php7-session \
&& wget https://files.phpmyadmin.net/phpMyAdmin/4.9.0.1/phpMyAdmin-4.9.0.1-all-languages.tar.gz \
&& tar xvf phpMyAdmin-4.9.0.1-all-languages.tar.gz \
&& mv phpMyAdmin-4.9.0.1-all-languages phpmyadmin \
&& apk add telegraf

ADD docker/start.sh /
ADD docker/config.inc.php phpmyadmin/
ADD docker/telegraf.conf etc/

EXPOSE 5000

CMD sh start.sh
