FROM alpine:latest

ADD docker/repositories /etc/apk

RUN apk update \
dd&& apk add php7 php7-fpm php7-opcache php7-gd php7-mysqli php7-zlib php7-curl php7-mbstring php7-json php7-session\
&& wget http://wordpress.org/latest.tar.gz \
&& tar -xzvf latest.tar.gz \
&& apk add telegraf

ADD docker/telegraf.conf / etc/
ADD docker/script.sh / 
ADD docker/wp-config.php wordpress/wp-config.php

EXPOSE 5050

#ENTRYPOINT php -S 0.0.0.0:5050 -t /wordpress

CMD sh script.sh
